// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtharSxLt9rEiJQPoa04-ObLZYyIEuoQg',
    appId: '1:369205638883:web:abab6743049856c24977d6',
    messagingSenderId: '369205638883',
    projectId: 'clinicease-c04d1',
    authDomain: 'clinicease-c04d1.firebaseapp.com',
    databaseURL: 'https://clinicease-c04d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clinicease-c04d1.firebasestorage.app',
    measurementId: 'G-2T0QD99KF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8TqZ5XG0Kom28XpZaTKsqzligF3LiFT0',
    appId: '1:369205638883:android:5ba6ffbb0e924d404977d6',
    messagingSenderId: '369205638883',
    projectId: 'clinicease-c04d1',
    databaseURL: 'https://clinicease-c04d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clinicease-c04d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvRqkDzIsJV027EprHNAMpv35ihUcL3j8',
    appId: '1:369205638883:ios:0d31353df3e3b4664977d6',
    messagingSenderId: '369205638883',
    projectId: 'clinicease-c04d1',
    databaseURL: 'https://clinicease-c04d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clinicease-c04d1.firebasestorage.app',
    iosBundleId: 'com.clinicease.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvRqkDzIsJV027EprHNAMpv35ihUcL3j8',
    appId: '1:369205638883:ios:ffde2ec74a401c204977d6',
    messagingSenderId: '369205638883',
    projectId: 'clinicease-c04d1',
    databaseURL: 'https://clinicease-c04d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clinicease-c04d1.firebasestorage.app',
    iosBundleId: 'com.example.clinicManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtharSxLt9rEiJQPoa04-ObLZYyIEuoQg',
    appId: '1:369205638883:web:5865328e9948087f4977d6',
    messagingSenderId: '369205638883',
    projectId: 'clinicease-c04d1',
    authDomain: 'clinicease-c04d1.firebaseapp.com',
    databaseURL: 'https://clinicease-c04d1-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'clinicease-c04d1.firebasestorage.app',
    measurementId: 'G-1Q3WK6QVHM',
  );

}